/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiIngestRouteImport } from './routes/api.ingest'
import { Route as AnalyticsDayMapRouteImport } from './routes/analytics.day-map'
import { Route as AnalyticsSectionRouteImport } from './routes/analytics.$section'
import { Route as AdminResourceRouteImport } from './routes/admin.$resource'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsDayMapRoute = AnalyticsDayMapRouteImport.update({
  id: '/day-map',
  path: '/day-map',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsSectionRoute = AnalyticsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AdminResourceRoute = AdminResourceRouteImport.update({
  id: '/admin/$resource',
  path: '/admin/$resource',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/analytics/$section': typeof AnalyticsSectionRoute
  '/analytics/day-map': typeof AnalyticsDayMapRoute
  '/api/ingest': typeof ApiIngestRoute
  '/admin/': typeof AdminIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/analytics/$section': typeof AnalyticsSectionRoute
  '/analytics/day-map': typeof AnalyticsDayMapRoute
  '/api/ingest': typeof ApiIngestRoute
  '/admin': typeof AdminIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/analytics/$section': typeof AnalyticsSectionRoute
  '/analytics/day-map': typeof AnalyticsDayMapRoute
  '/api/ingest': typeof ApiIngestRoute
  '/admin/': typeof AdminIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/health'
    | '/login'
    | '/admin/$resource'
    | '/analytics/$section'
    | '/analytics/day-map'
    | '/api/ingest'
    | '/admin/'
    | '/analytics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/admin/$resource'
    | '/analytics/$section'
    | '/analytics/day-map'
    | '/api/ingest'
    | '/admin'
    | '/analytics'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/health'
    | '/login'
    | '/admin/$resource'
    | '/analytics/$section'
    | '/analytics/day-map'
    | '/api/ingest'
    | '/admin/'
    | '/analytics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  AdminResourceRoute: typeof AdminResourceRoute
  ApiIngestRoute: typeof ApiIngestRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/day-map': {
      id: '/analytics/day-map'
      path: '/day-map'
      fullPath: '/analytics/day-map'
      preLoaderRoute: typeof AnalyticsDayMapRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/$section': {
      id: '/analytics/$section'
      path: '/$section'
      fullPath: '/analytics/$section'
      preLoaderRoute: typeof AnalyticsSectionRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/admin/$resource': {
      id: '/admin/$resource'
      path: '/admin/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AdminResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsSectionRoute: typeof AnalyticsSectionRoute
  AnalyticsDayMapRoute: typeof AnalyticsDayMapRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsSectionRoute: AnalyticsSectionRoute,
  AnalyticsDayMapRoute: AnalyticsDayMapRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  AdminResourceRoute: AdminResourceRoute,
  ApiIngestRoute: ApiIngestRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
