/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DayMapRouteImport } from './routes/day-map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiIngestRouteImport } from './routes/api.ingest'
import { Route as AdminResourceRouteImport } from './routes/admin.$resource'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DayMapRoute = DayMapRouteImport.update({
  id: '/day-map',
  path: '/day-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResourceRoute = AdminResourceRouteImport.update({
  id: '/admin/$resource',
  path: '/admin/$resource',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day-map': typeof DayMapRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/api/ingest': typeof ApiIngestRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day-map': typeof DayMapRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/api/ingest': typeof ApiIngestRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/day-map': typeof DayMapRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/api/ingest': typeof ApiIngestRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/day-map'
    | '/health'
    | '/login'
    | '/admin/$resource'
    | '/api/ingest'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/day-map'
    | '/health'
    | '/login'
    | '/admin/$resource'
    | '/api/ingest'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/day-map'
    | '/health'
    | '/login'
    | '/admin/$resource'
    | '/api/ingest'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DayMapRoute: typeof DayMapRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  AdminResourceRoute: typeof AdminResourceRoute
  ApiIngestRoute: typeof ApiIngestRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-map': {
      id: '/day-map'
      path: '/day-map'
      fullPath: '/day-map'
      preLoaderRoute: typeof DayMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$resource': {
      id: '/admin/$resource'
      path: '/admin/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AdminResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DayMapRoute: DayMapRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  AdminResourceRoute: AdminResourceRoute,
  ApiIngestRoute: ApiIngestRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
